### ISSUE TITLE
Periodically returning empty string in Node v5.4

### ISSUE THREAD

**Issue by bfricka** [robrich/pretty-hrtime#4]
This came about because I noticed that sometimes certain tasks would not show the finished output time (pretty-hrtime was returning an empty string).

[Node v5.4](https://github.com/nodejs/node/blob/master/CHANGELOG.md) changed `process.hrtime` so it can now return negative nanosecond values in cases where seconds are > 0.  Essentially, instead of representing 30.9 seconds as `[30, 9e8]` it will instead represent it as `[31, -1e8]`. The resulting total is the same, but it breaks this module.

**Comment by ben-eb** [comment]
@robrich Would it be possible to release this patch on npm please?

**Comment by robrich** [comment]
I was waiting for a PR that would solve the "100 seconds in a minute" bug too, but you're right, let's publish this sooner.

**Comment by bfricka** [comment]
Sorry @robrich. I did look at the bug for about 20 mins, but wasn't able to figure it out. I will look at it this weekend.

**Comment by robrich** [comment]
Published to npm: 1.0.2

**Comment by ben-eb** [comment]
Thanks! :+1:
